### ISSUE TITLE
메인 페이지 구성 Todo

### ISSUE THREAD

**Issue by nailnoy** [playdata-aichief-ai/aichief-nextjs-front#1]
# 📄 이슈 내용    
- 사이트를 대표하는 메인 페이지를 생성

# ✏️ To-do
- [x] 기초 레이아웃 구성 
- [x] 모바일 대응으로 반응형
- [x] AI 계장님의 특징을 보여줄 수 있는 문구가 포함된 Hero Component
- [x] AI 로직을 보여줄 수 있는 Feature Component
- [x] 에니메이션 추가로 심심하지 않게!
