### ISSUE TITLE
마이 프로필 구성 Todo

### ISSUE THREAD

**Issue by nailnoy** [playdata-aichief-ai/aichief-nextjs-front#3]
# 📄 이슈 내용    
- 회원의 정보를 확인 할 수 있는 마이 페이지 구성

# ✏️ To-do
- [x] 세션에 저장된 role로 화면의 구성을 다르게 랜더링
- [x] 개인정보의 조회와 수정이 가능하게
- [x] 각 조회내용 클릭시 상세 정보 표시
