### ISSUE TITLE
업로드 페이지 구현 Todo

### ISSUE THREAD

**Issue by nailnoy** [playdata-aichief-ai/aichief-nextjs-front#4]
# 📄 이슈 내용    
- 청구의 가장 중요한 부분인 업로드 페이지 구성

# ✏️ To-do
- [x] 고용량의 사진도 저장이 가능하게 구현 -> s3 버켓에 담아 스프링에 전달하는 것으로 해결
- [x] 청구자와 담당자의 업로드 화면 구성 다르게 -> 로직상 담당자의 업로드는 필수하지 않은 것으로 해결
- [x] 청구 사진 프리뷰
- [x] 사진과 해당하는 계약 선택 전에 청구 불가능하게
