### ISSUE TITLE
청구 상세보기 구현 Todo

### ISSUE THREAD

**Issue by nailnoy** [playdata-aichief-ai/aichief-nextjs-front#5]
# 📄 이슈 내용    
- 청구서를 조회, 검색할 수 있는 페이지 생성
- AI를 통해 분석이 끝난 청구서의 상세 내역의 확인과 수정을  할 수 있는 페이지 생성

# ✏️ To-do
- [x] 청구서 검색 페이지를 SSR방식으로 생성
- [ ] 검색을 통해 청구서 목록이 동적으로 렌더링되게 구현
- [ ] 상세 보기 화면에  청구서 사진을 띄워주기
- [x] 상세보기 페이지에서 해당 청구와 같은 청구자가 제출한 청구서 목록 띄워주기(SSG 방식)
